### ISSUE TITLE
Automatic room assignment does not work for arbitrary admission and discharge dates

### ISSUE THREAD

**Issue by JonasDju** [JonasDju/HospiTool#34]
### Describe the Bug
Since the patient-to-room assignment algorithm uses days as the smallest time unit, it may assign two patients to the same room if the first patients' discharge time is after the second patients' admission time (but both times are on the same day).  

### Expected Behavior
The algorithm recognizes that the room is occupied until the discharge time of the first patient and therefore does not assign another patient with an admission time earlier than the discharge time of the first patient to the same room.

### Additional Information
Solving this issue probably includes modifying the patient-to-room assignment algorithm available at [TabeaBrandt/patient-to-room_assignment](https://github.com/TabeaBrandt/patient-to-room_assignment/tree/v1) to use a more granular time unit like hours instead of days. Additionally, the last time unit (which may not completely be covered by the corresponding patients' stay) should be blocked for other patients such that no overlap (even for a few minutes) is possible.
After changing the algorithm to use hours instead of days, the code in this repository has to be adopted accordingly.

### TODOs
- [x] Fix file not found error on windows when using the docker container
- [x] Make the algorithm work with more than two beds per room
- [x] Make the algorithm work with hours instead of days as time units
- [x] Make our software gracefully handle crashes of the algorithm
- [x] Delete the generated json file after it has been loaded. Otherwise, old patient assignments get reloaded if the algorithm crashes
- [x] Let the user supply a gurobi license file

**Comment by JonasDju** [comment]
I just noticed that the algorithm seems to crash if any room in the ward has more than two beds.

```
Traceback (most recent call last):
  File "/bed-management/patient-to-room_assignment/call_from_django.py", line 34, in <module>
    call_from_django(f"instances/{file}", last_day)
  File "/bed-management/patient-to-room_assignment/call_from_django.py", line 24, in call_from_django
    result = assign_patients(patients, 0, last_day, rooms, current_assignment)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bed-management/patient-to-room_assignment/Dynamic.py", line 94, in assign_patients
    newResult = IP(
                ^^^
  File "/bed-management/patient-to-room_assignment/Ipr.py", line 296, in IP
    c(m, modelVars, useVarMrt, patients, rooms, firstDay, lastDay)
  File "/bed-management/patient-to-room_assignment/Iprt.py", line 10, in fix_smax
    assert all(
           ^^^^
AssertionError: upper bound on single rooms for private patients is only valid for rooms with at most two beds
Internal Server Error: /timeline/2/suggest/
Traceback (most recent call last):
  File "/bed-management/ycms/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/bed-management/ycms/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bed-management/ycms/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bed-management/ycms/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bed-management/ycms/.venv/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bed-management/ycms/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bed-management/ycms/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bed-management/ycms/ycms/cms/views/timeline/timeline_view.py", line 46, in get_context_data
    call_command("call_solver_api", pk, stdout=out)
  File "/bed-management/ycms/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 194, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bed-management/ycms/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bed-management/ycms/ycms/core/management/commands/call_solver_api.py", line 108, in handle
    with open(settings.PRA_OUTPUT_PATH, "r", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/bed-management/patient-to-room_assignment/Results/instances/generated_out.json'
[02/Dec/2024 21:50:18] "GET /timeline/2/suggest/ HTTP/1.1" 500 108087
```

Its obviously because of the assertion, but I have not yet looked into it.

**Comment by JonasDju** [comment]
I've changed the repository (patient-to-room_assignment) that is cloned to my forked version. This change is intended to be temporary until all necessary changes have been made to the algorithm. At this point, we can create a PR and move all changes to Tabea's repository.
